#!/bin/bash

TOP_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


# Compile BLAM packages.
cd ${TOP_DIR}/internal
echo 'Creating a ROS workspace for BLAM packages.'
catkin_make --cmake-args -DCMAKE_BUILD_TYPE=Release
source ${TOP_DIR}/internal/devel/setup.bash --extend
